// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdateAndRestart() {
  return window['go']['main']['App']['ApplyUpdateAndRestart']();
}

export function BackupDatabase() {
  return window['go']['main']['App']['BackupDatabase']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearNotifications() {
  return window['go']['main']['App']['ClearNotifications']();
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteNotification(arg1) {
  return window['go']['main']['App']['DeleteNotification'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DesktopNotificationsAvailable() {
  return window['go']['main']['App']['DesktopNotificationsAvailable']();
}

export function DismissUpdate() {
  return window['go']['main']['App']['DismissUpdate']();
}

export function ExportTasksCSV() {
  return window['go']['main']['App']['ExportTasksCSV']();
}

export function GetDataLocations() {
  return window['go']['main']['App']['GetDataLocations']();
}

export function GetDataPath() {
  return window['go']['main']['App']['GetDataPath']();
}

export function GetMailQueueStats() {
  return window['go']['main']['App']['GetMailQueueStats']();
}

export function GetMailSettings() {
  return window['go']['main']['App']['GetMailSettings']();
}

export function GetNotifyPrefs() {
  return window['go']['main']['App']['GetNotifyPrefs']();
}

export function GetUpdateInfo() {
  return window['go']['main']['App']['GetUpdateInfo']();
}

export function GetUpdateSettings() {
  return window['go']['main']['App']['GetUpdateSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListMailQueue() {
  return window['go']['main']['App']['ListMailQueue']();
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function ListNotifications() {
  return window['go']['main']['App']['ListNotifications']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function MarkAllNotificationsRead() {
  return window['go']['main']['App']['MarkAllNotificationsRead']();
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['App']['MarkNotificationRead'](arg1);
}

export function OpenLocalPath(arg1) {
  return window['go']['main']['App']['OpenLocalPath'](arg1);
}

export function OpenUpdatePackage() {
  return window['go']['main']['App']['OpenUpdatePackage']();
}

export function PurgeMailQueue() {
  return window['go']['main']['App']['PurgeMailQueue']();
}

export function RefitWindow(arg1, arg2) {
  return window['go']['main']['App']['RefitWindow'](arg1, arg2);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RestoreDatabase() {
  return window['go']['main']['App']['RestoreDatabase']();
}

export function RetryAllMail() {
  return window['go']['main']['App']['RetryAllMail']();
}

export function RetryMailItem(arg1) {
  return window['go']['main']['App']['RetryMailItem'](arg1);
}

export function SaveMailPrefs(arg1) {
  return window['go']['main']['App']['SaveMailPrefs'](arg1);
}

export function SaveNotifyPrefs(arg1) {
  return window['go']['main']['App']['SaveNotifyPrefs'](arg1);
}

export function SaveSMTPConfig(arg1) {
  return window['go']['main']['App']['SaveSMTPConfig'](arg1);
}

export function SendMailNow(arg1) {
  return window['go']['main']['App']['SendMailNow'](arg1);
}

export function SendNotificationNow(arg1) {
  return window['go']['main']['App']['SendNotificationNow'](arg1);
}

export function SetTaskDueDate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTaskDueDate'](arg1, arg2, arg3);
}

export function SetTaskProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTaskProject'](arg1, arg2, arg3);
}

export function SetUpdatePollInterval(arg1) {
  return window['go']['main']['App']['SetUpdatePollInterval'](arg1);
}

export function TestNotification() {
  return window['go']['main']['App']['TestNotification']();
}

export function TestSMTP() {
  return window['go']['main']['App']['TestSMTP']();
}

export function ToggleTaskDone(arg1) {
  return window['go']['main']['App']['ToggleTaskDone'](arg1);
}

export function UnreadNotificationCount() {
  return window['go']['main']['App']['UnreadNotificationCount']();
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}

export function WipeDatabase() {
  return window['go']['main']['App']['WipeDatabase']();
}

export function WipeLocalData(arg1) {
  return window['go']['main']['App']['WipeLocalData'](arg1);
}
