// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdateAndRestart() {
  return window['go']['main']['App']['ApplyUpdateAndRestart']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DismissUpdate() {
  return window['go']['main']['App']['DismissUpdate']();
}

export function ExportTasksCSV() {
  return window['go']['main']['App']['ExportTasksCSV']();
}

export function GetUpdateInfo() {
  return window['go']['main']['App']['GetUpdateInfo']();
}

export function GetUpdateSettings() {
  return window['go']['main']['App']['GetUpdateSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenUpdatePackage() {
  return window['go']['main']['App']['OpenUpdatePackage']();
}

export function RefitWindow(arg1, arg2) {
  return window['go']['main']['App']['RefitWindow'](arg1, arg2);
}

export function SetTaskDueDate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTaskDueDate'](arg1, arg2, arg3);
}

export function SetTaskProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTaskProject'](arg1, arg2, arg3);
}

export function SetUpdatePollInterval(arg1) {
  return window['go']['main']['App']['SetUpdatePollInterval'](arg1);
}

export function ToggleTaskDone(arg1) {
  return window['go']['main']['App']['ToggleTaskDone'](arg1);
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
