// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdateAndRestart():Promise<void>;

export function CheckForUpdates():Promise<void>;

export function CreateNote(arg1:main.NoteInput):Promise<main.Note>;

export function CreateProject(arg1:main.ProjectInput):Promise<main.Project>;

export function CreateTask(arg1:main.TaskInput):Promise<main.Task>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function DismissUpdate():Promise<void>;

export function ExportTasksCSV():Promise<string>;

export function GetUpdateInfo():Promise<main.UpdateInfo>;

export function GetUpdateSettings():Promise<main.UpdateSettings>;

export function GetVersion():Promise<string>;

export function ListNotes():Promise<Array<main.Note>>;

export function ListProjects():Promise<Array<main.Project>>;

export function ListTasks():Promise<Array<main.Task>>;

export function OpenUpdatePackage():Promise<void>;

export function RefitWindow(arg1:number,arg2:number):Promise<void>;

export function SetTaskDueDate(arg1:number,arg2:any,arg3:number):Promise<main.Task>;

export function SetTaskProject(arg1:number,arg2:any,arg3:number):Promise<main.Task>;

export function SetUpdatePollInterval(arg1:string):Promise<void>;

export function ToggleTaskDone(arg1:number):Promise<main.Task>;

export function UpdateNote(arg1:main.NoteInput):Promise<main.Note>;

export function UpdateProject(arg1:main.ProjectInput):Promise<main.Project>;

export function UpdateTask(arg1:main.TaskInput):Promise<main.Task>;
